### ISSUE TITLE
The plugin crashes on .NET 6 when trying to open a customized website

### ISSUE THREAD

**Issue by wizcas** [harrynull/Flow.Launcher.Dictionary#19]
`System.Diagnostics.Process.Start()` fails to open a URL if the runtime is .NET 6. 

The key part of the error log is:

```
Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/28/2022 19:20:40
Exception:
System.ComponentModel.Win32Exception (2): 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(String fileName)
   at Dictionary.Main.<>c__DisplayClass23_0.<MakeResultItem>b__4(ActionContext e) in C:\Users\Null\Documents\Projects\Flow.Launcher.Dictionary\src\Dictionary.cs:line 111
```

**Comment by wizcas** [comment]
Hey @harrynull 👋 I just submit a PR trying to fix this. Could you please take a look?

**Comment by harrynull** [comment]
Hey! Thank you so much for reporting this bug and even making a PR. I personally do not use this functionality so I did not notice that it has been broken for a while. I'm going to take a look, merge the PR and release a new version some time later today or tomorrow.

**Comment by wizcas** [comment]
Please take your time 👍 This plugin is such a wonderful job!

**Comment by harrynull** [comment]
Thank you! I'm so happy that you like this plugin :)
