### ISSUE TITLE
Admin account required and Windows Media Player Legacy access.

### ISSUE THREAD

**Issue by johnnymatthews** [harrynull/Flow.Launcher.Dictionary#28]
Tried to download a dictionary, but ran into this error:

```
1. upload log file: C:\Users\johnny\AppData\Roaming\FlowLauncher\Logs\1.18.0\2024-05-06.txt
2. copy below exception message

Flow Launcher version: 1.18.0
OS Version: 22631.3527
IntPtr Length: 8
x64: True

Python Path: 
Node Path: 
Date: 05/06/2024 15:33:43
Exception:
Dictionary Exception: 
Websites: https://github.com/harrynull/Flow.Launcher.Dictionary
Author: Harry Yu
Version: 2.3.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: SQLite Error 14: 'unable to open database file'.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Dictionary.ECDict.Query(String word) in C:\Users\Null\Documents\Projects\Flow.Launcher.Dictionary\src\ECDict.cs:line 43
   at Dictionary.Main.FirstLevelQueryAsync(Query query, CancellationToken token) in C:\Users\Null\Documents\Projects\Flow.Launcher.Dictionary\src\Dictionary.cs:line 165
   at Dictionary.Main.QueryAsync(Query query, CancellationToken token) in C:\Users\Null\Documents\Projects\Flow.Launcher.Dictionary\src\Dictionary.cs:line 380
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 325
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Here's some relevant error messages from the log file:

```
10:05:30.3687-03:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
10:05:30.3687-03:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player Legacy.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
10:05:30.3687-03:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
10:05:30.4249-03:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
10:05:30.4249-03:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
10:05:30.4249-03:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
10:24:56.0862-03:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
10:24:56.0862-03:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Windows Media Player Legacy.lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
10:24:56.0862-03:00 - ERROR -  - ------------- END Flow.Launcher.Plugin.Program exception -------------
10:24:56.1057-03:00 - ERROR -  - ------------- BEGIN Flow.Launcher.Plugin.Program exception -------------
10:24:56.1057-03:00 - ERROR -  - 
Exception full name: System.Runtime.InteropServices.COMException
Error status: UNKNOWN
Class name: IShellLinkW
Calling method: retrieveTargetPath
Program path: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk
InnerException number: 1
Exception message: Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception error type: HResult -2147467259
Exception thrown in called method: Void GetDescription(System.Text.StringBuilder, Int32)
Possible interpretation of the error: Error caused likely due to trying to get the description of the program
Possible resolution: Not yet known
```

This plugin is looking for access to:

- Windows Media Player Legacy
- ODBC Data Sources (32-bit)

Not sure why it needs access to Windows Media Player. And the ODBC Data Sources link is an admin only too. Why does a dictionary need admin access?

**Comment by harrynull** [comment]
I don't think the second stack trace re WMP is related to my plugin. The first one might be caused by a corrupted database file. Could you try removing the db file / manually download one? README has instructions on how to do that.

**Comment by johnnymatthews** [comment]
For sure. I don't have access to my Windows machine right now, but can try it later this week.

**Comment by harrynull** [comment]
Closed due to inactivity
